# Generated by Django 5.2.8 on 2025-11-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='username_usuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='username_usuario',
            new_name='id_usuario',
        ),
    ]
