# Generated by Django 5.2.6 on 2025-09-13 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 21, 2, 35, 971815)),
        ),
    ]
