# Generated by Django 5.2.6 on 2025-09-13 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_nome_completo_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 21, 20, 27, 979213)),
        ),
    ]
