# Generated by Django 5.2.6 on 2025-09-15 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_postagem_data_alter_postagem_imagem_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 20, 35, 34, 550281)),
        ),
    ]
