# Generated by Django 5.2.6 on 2025-09-15 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='setor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 20, 41, 28, 814551)),
        ),
    ]
