# Generated by Django 5.2.6 on 2025-09-16 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_noticia_setor_alter_postagem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.CharField(default=None, max_length=220),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 14, 4, 13, 701261)),
        ),
    ]
