# Generated by Django 5.2.6 on 2025-09-16 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_noticia_link_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 15, 2, 0, 712383)),
        ),
    ]
