# Generated by Django 5.2.6 on 2025-09-16 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_noticia_data_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, max_length=200, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 16, 44, 5, 11183)),
        ),
    ]
