# Generated by Django 5.2.6 on 2025-09-16 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_noticia_imagem_alter_postagem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 20, 33, 29, 554383)),
        ),
    ]
