# Generated by Django 5.2.6 on 2025-09-17 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_noticia_imagem_url_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 21, 8, 17, 321406)),
        ),
    ]
