# Generated by Django 5.2.6 on 2025-09-29 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_postagem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postagem',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 20, 16, 2, 751677)),
        ),
    ]
