# Generated by Django 5.2.6 on 2025-09-29 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_noticia_disponivel_postagem_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 20, 28, 33, 323281)),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
