# Generated by Django 5.2.6 on 2025-09-30 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_noticia_disponivel_alter_postagem_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 21, 27, 20, 3961)),
        ),
    ]
