# Generated by Django 5.2.6 on 2025-10-01 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='setor',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 17, 14, 41, 94193)),
        ),
    ]
