# Generated by Django 5.2.6 on 2025-10-01 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_noticia_setor_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='setor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 1, 17, 16, 51, 61347)),
        ),
    ]
